# Starter pipeline
- task: PowerShell@2
  inputs:
    filePath: '[CmdletBinding()] param (     $ApiManagementServiceName,     $ApiManagementServiceResourceGroup )  $apimServiceName = $ApiManagementServiceName $resourceGroupName = $ApiManagementServiceResourceGroup  Write-Host "Api Management Service Name: $($apimServiceName)" Write-Host "Api Management Resource Group Name: $($resourceGroupName)"'
    arguments: '-ApiManagementServiceName $(ApiManagementServiceName) -ApiManagementServiceResourceGroup $(ApiManagementServiceResourceGroup)'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
